# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3dfd68da802c2f1ccca0830fdc5e829437885ba61a4b5f5a09a726e7b8a118c1d05513e67b287962890c4eb81740f930000d482084a048995665097d2da6a7e2

test:
  secret_key_base: 425a8213da04b154464d4000529fe83f805d048100dcca49c1b0c30b302c84d1c6305623513587a3382a03915b4c6b4d8ba9f129aac9070fb348a3aa7606ab8d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
